- README.md
A few badge changes, pretty self-explanatory.
> Small badge changes

- .github/workflows/git-bat.yml
- .prettierignore
- bijou.js
Reverts Explosion-Scratch/bijou.js#5
> Revert "Get workflow working"

- .github/workflows/git-bat.yml
- .prettierignore
- bijou.js
Reverts Explosion-Scratch/bijou.js#6
> Revert "Revert "Get workflow working""

- README.md
I said comma when I meant quote... whoops
> Forgot a quote in README

- LICENSE.md
- README.md
> Add word "Contributors"

- README.md
> fix my and @TheColaber’s names

- README.md
> Update README.md to be a bit more descriptive AND FIX THE NAMES 😒

- 404.html
- README.html
- README.md
- bijou.js
- image.html
- index.html
- try.html
Reverts Bijou-js/Bijou.js#65
------
Sorry @AmpersandGD, I appreciate the help, but I can't actually figure out what is and isn't changed, not to mention the typos and stuff! I'll add you to the contributors in the source file though. If you want to redo the PR and state what exactly you changed in each file that'd be fine! =)
> Revert #65

- bijou.js
> Fix curryFunction recursion

- bijou.js
> Add default values to _$.listen cbs

- bijou.js
> remove function: return array rather than removed item

- bijou.js
> Fix preloadImage

- js/_end.js
- js/utility.js
It’s amazing.
Explosion told me to PR it.
> add soundex algorithm

- js/array.js
- js/date.js
- js/element.js
- js/math.js
- js/string.js
- js/utility.js
Makes use of @function consistent, some other small things.
> Small jsdoc clean up

- .github/workflows/build.yml
- bijou.d.ts
- js/math.js
- js/string.js
- package.json
> Typescript

- js/element.js
_$.create now works B)
(lol so many broken functions, one by one we will find them. And ~~destroy~~ fix them.)
> Fix _$.create()

- js/utility.js
New preload function, from https://gist.github.com/Explosion-Scratch/78401fdab59aa3c7eed25be3e0a3015c, still really glitchy and probably will cause bugs with bijou.
> New preload function

- js/element.js
Resolves #275 
This does use optional chaining - is that ok or do we need good browser support?
> Fix fullScreen for firefox

- js/math.js
- js/utility.js
I think this is all correct, might not be though
> add object jsdoc stuff

- js/element.js
- js/event.js
- js/utility.js
Promises can only be resolved once
> remove some promises

- js/element.js
- js/event.js
- js/utility.js
> Revert "remove some promises"

- js/array.js
- js/element.js
- js/event.js
- js/function.js
- js/math.js
- js/object.js
- js/string.js
> Callback jsdoc

- package-lock.json
- package.json
> Revert "Bump clean-jsdoc-theme from 3.3.4 to 4.0.4"
